In [1]:
pip install -U fortran-magic

Requirement already up-to-date: fortran-magic in /usr/local/lib/python3.6/dist-packages (0.7)


In [32]:
%matplotlib inline
%reload_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])
print(event_values)

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


[10 15 20]


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [33]:
assert ran_the_first_cell, "Oh noes!"

In [34]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [35]:
l2 = [1412, 'one', 314.064, 423, 54.065, "two"]
l2

[1412, 'one', 314.064, 423, 54.065, 'two']

In [36]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [37]:
first2 = l2[0]
second2 = l2[1]
print("first:", first2)
print("second:", second2)

first: 1412
second: one


In [38]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [39]:
last2 = l2[-1]
penultimate2 = l2[-2]
print("last:", last2)
print("second to last:", penultimate2)

last: two
second to last: 54.065


In [40]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [41]:
sublist2 = l2[1:3]
sublist2

['one', 314.064]

In [42]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [43]:
first_three2 = l2[:3]
first_three2

[1412, 'one', 314.064]

In [44]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [45]:
after_three2 = l2[3:]
after_three2

[423, 54.065, 'two']

In [46]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [47]:
l2 = ['a1', '4b', 'sc', 'hd', 'eg', 'fd', 'gk','hh']
l2[1:7:2]

['4b', 'hd', 'fd']

In [48]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [49]:
l2[::-1]

['hh', 'gk', 'fd', 'eg', 'hd', 'sc', '4b', 'a1']

In [50]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [51]:
l2 = [41, 52, 36, 48, 95]
print("Before:", l2)
l2.append('six')
print("After:", l2)

Before: [41, 52, 36, 48, 95]
After: [41, 52, 36, 48, 95, 'six']


In [52]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [53]:
l2 = [14, 232, 3421, 2344, 24355]
[x * 2 for x in l2]

[28, 464, 6842, 4688, 48710]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [54]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [55]:
philosophers2 = {'Daid': 'Hme', 'Immnuel': 'Kat', 'Berand': 'Russ el'}
philosophers2

{'Berand': 'Russ el', 'Daid': 'Hme', 'Immnuel': 'Kat'}

In [56]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [57]:
philosophers2['Luwig'] = 'Wittstein'
philosophers2

{'Berand': 'Russ el', 'Daid': 'Hme', 'Immnuel': 'Kat', 'Luwig': 'Wittstein'}

In [58]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [59]:
del philosophers2['Daid']
philosophers2

{'Berand': 'Russ el', 'Immnuel': 'Kat', 'Luwig': 'Wittstein'}

In [60]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [70]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [71]:
a2 = [[1312, 1342, 51323],
     [2512, 33546, 4354],
     [41325, 6243, 752334],
     [1215, 15231, 1]]

b2 = [[113541, 2, 315132, 4],
     [2, 312351, 4, 55123541]]

In [72]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [73]:
%%time

matmul(a, b)

CPU times: user 19 µs, sys: 2 µs, total: 21 µs
Wall time: 24.1 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [150]:
np.matmul(np.array(a), np.array(b))

ValueError: ignored

In [151]:
np.matmul(np.array(b), np.array(a))

array([[24, 30, 36],
       [33, 42, 51]])

In [74]:
%%time

matmul(a2, b2)

CPU times: user 24 µs, sys: 0 ns, total: 24 µs
Wall time: 26.5 µs


[[148968476, 419177666, 413458552, 73975797270],
 [285282084, 10478131670, 791745768, 1849174316434],
 [4692094311, 1950089943, 13022854872, 344136431763],
 [137982777, 4757420511, 382946304, 839586657831]]

In [75]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.7818923274755317, 0.6741092986649222, 0.16646450565763582],
 [0.8778073278025953, 0.9884168016071064, 0.16295660741818696]]

In [76]:
randm2 = random_matrix(3, 5)
randm2

[[0.9313725505825036,
  0.55580325241349,
  0.14436827500263594,
  0.7094125430698442,
  0.54708131043446],
 [0.39817322294503266,
  0.6958464722407761,
  0.1081354337234891,
  0.07681910254989122,
  0.8141357019916224],
 [0.5940932483886168,
  0.5148028416456771,
  0.7160946498871488,
  0.800725240827442,
  0.5184686603843007]]

In [77]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 6.67 s, sys: 12.6 ms, total: 6.68 s
Wall time: 6.7 s


In [78]:
%%time
randa2 = random_matrix(500, 200)
randb2 = random_matrix(200, 500)
x2 = matmul(randa2, randb2)

CPU times: user 9.71 s, sys: 21.5 ms, total: 9.73 s
Wall time: 9.73 s


In [79]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [80]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [81]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [82]:
list_data2 = [float(i) for i in range(1012210)]
array_data2 = np.array(list_data2)

In [83]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 7.36 ms, sys: 12 µs, total: 7.37 ms
Wall time: 7.35 ms


333328333350000.0

In [84]:
%%time
python_dot_product(list_data2, list_data2)

CPU times: user 85.4 ms, sys: 0 ns, total: 85.4 ms
Wall time: 88 ms


3.456925119209051e+17

In [85]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 192 µs, sys: 0 ns, total: 192 µs
Wall time: 199 µs


333328333350000.0

In [86]:
%%time
fortran_dot_product(array_data2, array_data2)

CPU times: user 1.95 ms, sys: 0 ns, total: 1.95 ms
Wall time: 1.96 ms


3.456925119209051e+17

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [87]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [88]:
mul_elemwise([521, 26234, 3234, 4], [1234, 23 + 510j, 31324.534, 'four'])

[642914, (603382+13379340j), 101303542.956, 'fourfourfourfour']

In [89]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


In [90]:
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [91]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [92]:
data2 = np.array([144132, 51322, 352352, 51234])
data2

array([144132,  51322, 352352,  51234])

In [93]:
data + data

array([2, 4, 6, 8])

In [94]:
data2 + data2

array([288264, 102644, 704704, 102468])

In [95]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 766 µs, sys: 1.88 ms, total: 2.65 ms
Wall time: 1.76 ms


333328333350000.0

In [96]:
%%time
# Naive dot product
(array_data2 * array_data2).sum()

CPU times: user 5.49 ms, sys: 4.03 ms, total: 9.52 ms
Wall time: 16.5 ms


3.45692511921247e+17

In [97]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 4.07 ms, sys: 32 µs, total: 4.11 ms
Wall time: 4.26 ms


333328333350000.0

In [98]:
%%time
# Built-in dot product.
array_data2.dot(array_data2)

CPU times: user 1.47 ms, sys: 944 µs, total: 2.41 ms
Wall time: 1.32 ms


3.456925119211536e+17

In [99]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 197 µs, sys: 0 ns, total: 197 µs
Wall time: 204 µs


333328333350000.0

In [100]:
%%time
fortran_dot_product(array_data2, array_data2)

CPU times: user 1.85 ms, sys: 0 ns, total: 1.85 ms
Wall time: 1.86 ms


3.456925119209051e+17

In [101]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [102]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [103]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [104]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [105]:
arr2 = np.array([14132, 25123, 3135, 45132, 6235, 3416], dtype='int16').reshape(2, 3)
print("Array:\n", arr2, sep='')
print("===========")
print("DType:", arr2.dtype)
print("Shape:", arr2.shape)
print("Strides:", arr2.strides)
print("Data:", arr2.data.tobytes())

Array:
[[ 14132  25123   3135]
 [-20404   6235   3416]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'47#b?\x0cL\xb0[\x18X\r'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [106]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [107]:
data2 = np.arange(15).reshape(3, 5)
data2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [109]:
data2 * data2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [110]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [111]:
np.sqrt(data2)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [112]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [113]:
(data2 % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [114]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [115]:
((data2 % 2) == 0) & ((data2 % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [116]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [117]:
data2 @ data2.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [118]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [119]:
sines2 = np.sin(np.linspace(0, 3.14, 10))
cosines2 = np.cos(np.linspace(0, 3.14, 10))
sines2

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [120]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [121]:
sines2[0]

0.0

In [122]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [123]:
sines2[:4]

array([0.        , 0.34185385, 0.64251645, 0.86575984])

In [124]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [125]:
sines2[7:]

array([0.64373604, 0.34335012, 0.00159265])

In [126]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [127]:
sines2[::3]

array([0.        , 0.86575984, 0.8665558 , 0.00159265])

In [128]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [129]:
print("sines:\n", sines2)
print("sines > 0.5:\n", sines2 > 0.6)
print("sines[sines > 0.5]:\n", sines2[sines2 > 0.6])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [131]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [132]:
print(sines2)
sines2[[1, 3, 5]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.34185385, 0.86575984, 0.98496101])

In [133]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [134]:
unsorted_data2 = np.array([134132, 35123, 22452, 125243, -1576, 53413, 25432])

In [135]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [136]:
sort_indices2 = np.argsort(unsorted_data2)
sort_indices2

array([4, 2, 6, 1, 5, 3, 0])

In [137]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [138]:
unsorted_data2[sort_indices2]

array([ -1576,  22452,  25432,  35123,  53413, 125243, 134132])

In [139]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [140]:
market_caps2 = np.array([12135123, 623452, 1345630, 552143, 624376])  # Presumably in dollars?
assets2 = np.array(['AB', 'BA', 'FC', 'GD', 'RE'])

In [141]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [142]:
sort_by_mcap2 = np.argsort(market_caps2)
assets2[sort_by_mcap2]

array(['GD', 'BA', 'RE', 'FC', 'AB'], dtype='<U2')

In [143]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [144]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [145]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [146]:
data2 = np.arange(25).reshape(5, 5)
data2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [147]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [148]:
data2[:3, :3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [149]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [152]:
data2[:3, [0, -2]]

array([[ 0,  3],
       [ 5,  8],
       [10, 13]])

In [153]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [154]:
data2[(data2[:, 1] % 2) == 0]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [155]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [156]:
variance(np.random.standard_normal(1000))

0.9542601155369022

In [157]:
variance(np.random.standard_normal(2450))

0.9907844801579127

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [158]:
data = np.arange(30)
data.mean()

14.5

In [159]:
data2 = np.arange(77)
data2.mean()

38.0

- ...but we can do more interesting things with multi-dimensional arrays.

In [160]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [161]:
data2 = np.arange(30).reshape(3, 10)
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [162]:
data.mean()

14.5

In [163]:
data2.mean()

14.5

In [164]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [165]:
data2.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [166]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [167]:
data2.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [168]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [169]:
row2 = np.array([11432, 41232, 3512, 442])
column2 = np.array([[1341], [21342], [35123]])
print("Row:\n", row2, sep='')
print("Column:\n", column2, sep='')

Row:
[11432 41232  3512   442]
Column:
[[ 1341]
 [21342]
 [35123]]


In [170]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [171]:
row2 + column2

array([[12773, 42573,  4853,  1783],
       [32774, 62574, 24854, 21784],
       [46555, 76355, 38635, 35565]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [172]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [173]:
print("Data:\n", data2, sep='')
print("Mean:\n", data2.mean(axis=0), sep='')
print("Data - Mean:\n", data2 - data2.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [174]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [175]:
s2 = pd.Series(index=['af', 'bg', 'ch', 'jd', 'ke'], data=[114123, 243522, 345633, 44536, 35465])
s2

af    114123
bg    243522
ch    345633
jd     44536
ke     35465
dtype: int64

In [176]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [177]:
print("The index is:", s2.index)
print("The values are:", s2.values)

The index is: Index(['af', 'bg', 'ch', 'jd', 'ke'], dtype='object')
The values are: [114123 243522 345633  44536  35465]


In [178]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [179]:
s2.iloc[0]

114123

In [180]:
# ... or by label.
s.loc['a']

1

In [181]:
s2.loc['af']

114123

In [182]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [183]:
s2.iloc[:4]

af    114123
bg    243522
ch    345633
jd     44536
dtype: int64

In [184]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [185]:
s2.loc[:'ch']

af    114123
bg    243522
ch    345633
dtype: int64

In [186]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [187]:
s2.iloc[[0, -1]]

af    114123
ke     35465
dtype: int64

In [188]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [189]:
s2.loc[s2 > 44536]

af    114123
bg    243522
ch    345633
dtype: int64

In [190]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [191]:
other_s2 = pd.Series({'af': 14132.0, 'ch': 25234.0, 'jd': 31423.0, 'z': 425435.0})
other_s2

af     14132.0
ch     25234.0
jd     31423.0
z     425435.0
dtype: float64

In [192]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [193]:
s2 + other_s2

af    128255.0
bg         NaN
ch    370867.0
jd     75959.0
ke         NaN
z          NaN
dtype: float64

In [194]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [195]:
(s2 + other_s2).fillna(0.0)

af    128255.0
bg         0.0
ch    370867.0
jd     75959.0
ke         0.0
z          0.0
dtype: float64

In [196]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [197]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [198]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!